javascript:
  front:
    root: .
    filename: script.js
    vendor:
      - build/vendor/js/modernizr.js
      - build/vendor/js/fastclick.js
      - build/vendor/js/placeholder.js
      - build/vendor/js/jquery.cookie.js
      - build/vendor/js/realbig-slider.js
      - bower_components/foundation-sites/js/foundation.core.js
      - bower_components/foundation-sites/js/foundation.util.keyboard.js
      - bower_components/foundation-sites/js/foundation.util.box.js
      - bower_components/foundation-sites/js/foundation.util.nest.js
      - bower_components/foundation-sites/js/foundation.util.mediaQuery.js
      - bower_components/foundation-sites/js/foundation.util.triggers.js
      - bower_components/foundation-sites/js/foundation.util.motion.js
      - bower_components/foundation-sites/js/foundation.dropdownMenu.js
      - bower_components/foundation-sites/js/foundation.offcanvas.js
      - bower_components/foundation-sites/js/foundation.reveal.js
    notification: 'Running JavaScript'
    src:
      - 'build/js/**/*.js'
      - '!build/vendor/js/html5.js'
      - '!build/js/admin/**/*.js'
      - '!build/js/tinymce/**/*.js'
  admin:
    root: .
    filename: admin.js
    vendor: ""
    notification: 'Running Admin JavaScript'
    src:
      - 'build/js/admin/**/*.js'
  tinymce:
    root: ./tinymce/
    notification: 'Running TinyMCE JavaScript'
    src:
      - 'build/js/tinymce/**/*.js'
sass:
  compatibility:
    - 'last 2 versions'
    - 'ie >= 9'
  front:
    root: ./
    filename: style.css
    vendor:
      - bower_components/foundation-sites/scss
    notification: 'Running Sass'
    src: build/sass/main.scss
  admin:
    root: ./assets/css
    filename: admin.css
    vendor: ""
    notification: 'Running Admin Sass'
    src: build/sass/admin/main.scss
watch:
  javascript:
    front:
      - 'build/js/**/*.js'
      - '!build/js/admin/**/*.js'
      - '!build/js/tinymce/**/*.js'
    admin: 'build/js/admin/**/*.js'
    tinymce: 'build/js/tinymce/**/*.js'
  sass:
    front:
      - 'build/sass/**/*.scss'
      - '!build/sass/admin/**/*.scss'
    admin: 'build/sass/admin/**/*.scss'
release:
  type: theme
  languagesDir: ./languages/
  files:
    - './**/*.*'
    - '!./**/*.map'
    - '!./build/**/*.*'
    - '!./**/.git/**'
    - '!./**/.gitignore'
    - '!./**/.gitmodules'
    - '!./**/gulpfile.js'
    - '!./**/gruntfile.js'
    - '!./gulp/**/*.*'
    - '!./**/package.json'
    - '!./**/bower.json'
    - '!./node_modules/**/*.*'
    - '!./**/bower_components/**/*.*'
    - '!./README.md'
    - '!./*.zip'